import { defineConfig } from 'prisma/config'

export default defineConfig({
  datasource: {
    url: "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza183Z3JKV19fNkx3YXZETXF2RU9tNGYiLCJhcGlfa2V5IjoiMDFLUEFBU0hLSFBaVFFQNUVCTURCUTUxU1MiLCJ0ZW5hbnRfaWQiOiI0MGVmMTMzZGM3YmVhMGUwMDdkOTAwMmYwMjk4MWU4NGMzNWQ0ZGM4YjdiMGIwMTliZDI0ZWQyNTNhNTZhOGE0IiwiaW50ZXJuYWxfc2VjcmV0IjoiZGI5NWQ3YzAtYWZjOS00NmM0LWE5ZmMtOTQ1ODE2NzhiYjQxIn0.yHnm7cHe28q6vlnkZLP3hN7yGkfU99OoH3jW0TJbQUU",
  },
}) 